apiVersion: v1
data:
  # SERVER_PROFILE_URL: https://rlylepingidentity:ff63c171b7cca1d86e854d0dba74447ebc5dfe1b@github.com/Technical-Enablement-PingIdentity/BXFinance.git
  SERVER_PROFILE_PATH: pingdatagovernance
kind: ConfigMap
metadata:
  labels:
    role: pingdatagovernance
  name: pingdatagovernance-environment-variables
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingdatagovernance
  name: pingdatagovernance
spec:
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    role: pingdatagovernance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: pingdatagovernance
  name: pingdatagovernance
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pingdatagovernance
  template:
    metadata:
      labels:
        role: pingdatagovernance
      name: pingdatagovernance
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: shared-vars
        - secretRef:
            name: server-profile-url
            optional: false
        - secretRef:
            name: devops-secret
            optional: true
        - configMapRef:
            name: pingdatagovernance-environment-variables
        image: pingidentity/pingdatagovernance:8.1.0.0-EA-edge
        name: pingdatagovernance
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
      initContainers:
      - name: init
        image: curlimages/curl:latest
        command: ['sh', '-c', 'until curl --connect-timeout 1 --silent -k https://pingdirectory:443/directory/v1 ; do echo waiting for pingdirectory ; sleep 3 ; done']
