apiVersion: v1
data:
  # SERVER_PROFILE_URL: https://rlylepingidentity:ff63c171b7cca1d86e854d0dba74447ebc5dfe1b@github.com/Technical-Enablement-PingIdentity/BXFinance.git
  SERVER_PROFILE_PATH: pingfederate
kind: ConfigMap
metadata:
  labels:
    role: pingfederate
  name: pingfederate-environment-variables
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingfederate
  name: pingfederate
spec:
  ports:
  - name: pf-console
    port: 9999
  - name: pf-runtime
    port: 9031
  selector:
    role: pingfederate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: pingfederate
  name: pingfederate
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pingfederate
  template:
    metadata:
      labels:
        role: pingfederate
      name: pingfederate
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: shared-vars
        - secretRef:
            name: server-profile-url
            optional: false
        - secretRef:
            name: devops-secret
            optional: true
        - configMapRef:
            name: pingfederate-environment-variables
        image: pingidentity/pingfederate:edge
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /pingfederate/app
            port: 9999
            scheme: HTTPS
          initialDelaySeconds: 100
          periodSeconds: 1
        name: pingfederate
        ports:
        - containerPort: 9999
        - containerPort: 9031
        readinessProbe:
          httpGet:
            path: /pingfederate/app
            port: 9999
            scheme: HTTPS
          periodSeconds: 10
        resources:
          limits:
            cpu: "1"
            memory: 1.5Gi
          requests:
            cpu: "1"
            memory: 1.5Gi
      initContainers:
      - name: init
        image: curlimages/curl:latest
        command: ['sh', '-c', 'until curl --connect-timeout 1 --silent -k https://pingdirectory:443/directory/v1 ; do echo waiting for pingdirectory ; sleep 3 ; done']


# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: nginx-public
#     nginx.ingress.kubernetes.io/backend-protocol: HTTPS
#   labels:
#     role: pingfederate
#   name: pingfederate
# spec:
#   rules:
#   - host: pingfederate-admin.${PING_IDENTITY_DEVOPS_DNS_ZONE}
#     http:
#       paths:
#       - backend:
#           serviceName: pingfederate
#           servicePort: 9999
#         path: /pingfederate
#       - backend:
#           serviceName: pingfederate
#           servicePort: 9999
#         path: /pf-admin-api
#   - host: pingfederate.${PING_IDENTITY_DEVOPS_DNS_ZONE}
#     http:
#       paths:
#       - backend:
#           serviceName: pingfederate
#           servicePort: 9031
#         path: /
#   tls:
#   - hosts:
#     # example pingfederate-admin.example.com
#     - pingfederate-admin.${PING_IDENTITY_DEVOPS_DNS_ZONE}
#     secretName: tls-secret
#   - hosts:
#     - pingfederate.${PING_IDENTITY_DEVOPS_DNS_ZONE}
#     secretName: tls-secret